/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'linzhenhuan' at '17-12-24 上午10:54' with Gradle 2.14.1
 *
 * @author linzhenhuan, @date 17-12-24 上午10:54
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
